#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hellp World!" > /var/www/html/index.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart
