#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.7
apt-get -y update
apt-get install haproxy=2.7.\*
echo "frontend http
        bind *:80
        mode http
        default_backend web-backend
    backend web-backend
        balance roundrobin
        server 1574-web-01 35.227.35.75
        server 1574-web-02 100.24.37.33" >> /etc/haproxy/haproxy.cfg

service haproxy restart
