#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive
mysqldump --all-databases -u root -p"$1" > backup.sql
sudo tar -cvzf "$(date +%d-%m-%Y).tar.gz" backup.sql
